### ISSUE TITLE
Average_response function error

### ISSUE THREAD

**Issue by CallowBrainProject** [3Tissue/MRtrix3Tissue#12] opened 2020-01-29 14:45 UTC
Hello,

I am trying to use the average_response function on my data set to do a group analysis of metrics like percent CSF_like tissue in voxels of the hippocampus of my cohort. 

I have gone through and created csf_response.txt for each subject that look like this...

```
# b-values: 0,1000
# command_history: /Applications/MRtrix3Tissue/bin/dwi2response dhollander dwi_corrected.mif wm_response.txt gm_response.txt csf_response.txt  (version=3Tissue_v5.2.8)"
2594.80110093322
46.2413080531229
```

However, when I run...

average_response AES101.Ex/csf_response.txt AES101.Rest/csf_response.txt AES102.Ex/csf_response.txt AES102.Rest/csf_response.txt AES104.Ex/csf_response.txt AES104.Rest/csf_response.txt AES107.Ex/csf_response.txt AES107.Rest/csf_response.txt AES108.Ex/csf_response.txt AES108.Rest/csf_response.txt AES109.Ex/csf_response.txt AES109.Rest/csf_response.txt AES110.Ex/csf_response.txt AES110.Rest/csf_response.txt AES111.Ex/csf_response.txt AES111.Rest/csf_response.txt AES113.Ex/csf_response.txt AES113.Rest/csf_response.txt AES114.Ex/csf_response.txt AES114.Rest/csf_response.txt AES115.Ex/csf_response.txt AES115.Rest/csf_response.txt AES116.Ex/csf_response.txt AES116.Rest/csf_response.txt AES117.Ex/csf_response.txt AES117.Rest/csf_response.txt AES118.Ex/csf_response.txt AES118.Rest/csf_response.txt AES119.Ex/csf_response.txt AES119.Rest/csf_response.txt AES120.Ex/csf_response.txt AES120.Rest/csf_response.txt AES121.Ex/csf_response.txt AES121.Rest/csf_response.txt AES122.Ex/csf_response.txt AES122.Rest/csf_response.txt AES123.Ex/csf_response.txt AES123.Rest/csf_response.txt AES124.Ex/csf_response.txt AES124.Rest/csf_response.txt AES126.Ex/csf_response.txt AES126.Rest/csf_response.txt AES127.Ex/csf_response.txt AES127.Rest/csf_response.txt AES129.Ex/csf_response.txt AES129.Rest/csf_response.txt AES130.Ex/csf_response.txt AES130.Rest/csf_response.txt AES133.Ex/csf_response.txt AES133.Rest/csf_response.txt AES134.Ex/csf_response.txt AES134.Rest/csf_response.txt AES136.Ex/csf_response.txt AES136.Rest/csf_response.txt AES137.Ex/csf_response.txt AES137.Rest/csf_response.txt AES138.Ex/csf_response.txt AES138.Rest/csf_response.txt AES139.Ex/csf_response.txt AES139.Rest/csf_response.txt average_response.txt

I get the following error...

[255a-280:/Volumes/DANIEL/AES_mrtrix] amos% ./mrtrix_calculate_avg.sh 
Number of subjects: 60
Error in file AES101.Ex/csf_response.txt: multi-shell response functions must have the same number of coefficients per b-value (line)

It seems like I do have 2 coefficients for the 2 bvalues...?

Is there something I am missing? Thanks for any help you can provide!

**Comment by jrussell9000** [comment] 2020-01-29 19:41
In contrast to earlier (current stable?) versions, it appears that the dwi2response script included with the 3Tissue fork prepends two comment lines to each response text file giving the b-values and the command history.  But average_response verifies the number of coefficients in each response file match the number of shells by counting the number of lines in the file.  So with single-shell data (plus b0), average_response would think you had 4 coefficients instead of 2.

The fix appears to be to remove the first two (commented) lines from each response file.

**Comment by thijsdhollander** [comment] 2020-01-30 00:14
Hi both,

Great to hear you're actively using SS3T-CSD in group analyses.  Yes, what you run into is entirely expected.  @jrussell9000 is correct that the problem you encounter is due to new comment-style lines in the response function files (by the way, they're just text files indeed, so you can just open and inspect them in any text editor).

However, the solution can be more simple!  To clarify first: the current MRtrix3Tissue (v 5.2.8) branches and adopts a lot of changes up so some point in September in the MRtrix3 `dev` branch.  Those changes will eventually hopefully be released in the next MRtrix3 "release".  Part of these changes (independent of MRtrix3Tissue) is to have some of these comment lines in output text files, i.e. such as the command history, etc...  In MRtrix3Tissue v5.2.8, all commands should also already work well with the comments (and indeed, most of the time just "correctly ignore" them).  So what you're facing here is effectively a limitation in backwards compatibility (with MRtrix3 RC3 and older) that will pop up just as well when the next MRtrix3 is released.

So the solution is to use the equivalent command in MRtrix3Tissue v5.2.8 (rather than MRtrix3 RC3) to average the response functions.  **This command has also changed to a new name** (which means you can't be mistaken at least): it's now `responsemean`.  The default behaviour of this command (i.e. how the output is calculated) has also slightly changed (it now includes a basic weighting in case some subjects' response functions would be wildly different in magnitude), but for all intents and purposes you can still just write "*we averaged the WM, GM and CSF response functions across all subjects*" when you document this, just like before.  And so, as mentioned above, `responsemean` correctly ignores those comment lines so it shouldn't run into the issue you encountered.

By the way, on this topic, the most important of these changes are documented here (currently!): https://3tissue.github.io/doc/install/release.html .  Taking those into account, you can also opt to run your entire analysis using MRtrix3Tissue; i.e. just taking care to look at the few commands that have changed their name (or options / interface); they're all documented on that page.  Now that I look at what I wrote there, it actually also documents the addition of these "comment lines" in text files. 🙂 

I hope that all makes sense.  Don't hesitate to ask/comment if it doesn't!

Cheers,
Thijs

**Comment by thijsdhollander** [comment] 2020-01-30 00:19
Just on the side, @CallowBrainProject , if you want to paste contents of files like that here, it's best to put it between triple backticks on the line before and after.  Otherwise, GitHub interprets some characters and uses them for formatting.  This includes lines started by a hash sign indeed. ;-)  I'll see if I can edit your post to fix this up, so it's not too confusing for future readers of your post.

**Comment by CallowBrainProject** [comment] 2020-01-30 01:38
Sorry, Thijs, for the poor formatting. I have an additional issue that I am running into now though.

I have created my average response function with responsemean.

An example of the average_response_wm.txt I am using.

```# command_history: /Applications/MRtrix3Tissue/bin/responsemean AES101.Ex/gm_response.txt AES101.Rest/gm_response.txt AES102.Ex/gm_response.txt AES102.Rest/gm_response.txt AES104.Ex/gm_response.txt AES104.Rest/gm_response.txt AES107.Ex/gm_response.txt AES107.Rest/gm_response.txt AES108.Ex/gm_response.txt AES108.Rest/gm_response.txt AES109.Ex/gm_response.txt AES109.Rest/gm_response.txt AES110.Ex/gm_response.txt AES110.Rest/gm_response.txt AES111.Ex/gm_response.txt AES111.Rest/gm_response.txt AES113.Ex/gm_response.txt AES113.Rest/gm_response.txt AES114.Ex/gm_response.txt AES114.Rest/gm_response.txt AES115.Ex/gm_response.txt AES115.Rest/gm_response.txt AES116.Ex/gm_response.txt AES116.Rest/gm_response.txt AES117.Ex/gm_response.txt AES117.Rest/gm_response.txt AES118.Ex/gm_response.txt AES118.Rest/gm_response.txt AES119.Ex/gm_response.txt AES119.Rest/gm_response.txt AES120.Ex/gm_response.txt AES120.Rest/gm_response.txt AES121.Ex/gm_response.txt AES121.Rest/gm_response.txt AES122.Ex/gm_response.txt AES122.Rest/gm_response.txt AES123.Ex/gm_response.txt AES123.Rest/gm_response.txt AES124.Ex/gm_response.txt AES124.Rest/gm_response.txt AES126.Ex/gm_response.txt AES126.Rest/gm_response.txt AES127.Ex/gm_response.txt AES127.Rest/gm_response.txt AES129.Ex/gm_response.txt AES129.Rest/gm_response.txt AES130.Ex/gm_response.txt AES130.Rest/gm_response.txt AES133.Ex/gm_response.txt AES133.Rest/gm_response.txt AES134.Ex/gm_response.txt AES134.Rest/gm_response.txt AES136.Ex/gm_response.txt AES136.Rest/gm_response.txt AES137.Ex/gm_response.txt AES137.Rest/gm_response.txt AES138.Ex/gm_response.txt AES138.Rest/gm_response.txt AES139.Ex/gm_response.txt AES139.Rest/gm_response.txt average_response_wm.txt  (version=3Tissue_v5.2.8)"
9.12762362365042e+02
3.36046703707677e+02
# comments: ```
I use the following command
```ss3t_csd_beta1 dwi_corrected.mif /Volumes/DANIEL/AES_mrtrix/average_response_wm.txt wmfod.mif /Volumes/DANIEL/AES_mrtrix/average_response_gm gm.mif /Volumes/DANIEL/AES_mrtrix/response_csf.txt csf.mif -mask dwi_mask.mif```

but I get the following error

```subj =  AES139 , cond =  Ex
ss3t_csd_beta1: 
ss3t_csd_beta1: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
ss3t_csd_beta1: 
ss3t_csd_beta1: -------
ss3t_csd_beta1: 2 unique b-value(s) detected: 0,1000 with 1,64 volumes
ss3t_csd_beta1: -------
ss3t_csd_beta1: Importing response functions:
ss3t_csd_beta1: * Importing SF WM response function...

ss3t_csd_beta1: [ERROR] Single-fibre WM response file (/Volumes/DANIEL/AES_mrtrix/average_response_wm.txt) contains 2 lines, respectively with 1 and 1 coefficients. A minimum of 5 coefficients (lmax at least 8) is required for each line, and the number of coefficients has to match for both lines.```

...hopefully, the formatting is better this time!

**Comment by thijsdhollander** [comment] 2020-01-30 05:23
No worries at all about the formatting; it was an easy fix (and I could see / understand what you were typing there before for sure).

Ok, about the error; I'm quite happy I implemented a very thorough check on the response functions, so it does make it a bit easier to immediately see what the problem is.  What this bit tells you:

```
ss3t_csd_beta1: [ERROR] Single-fibre WM response file (/Volumes/DANIEL/AES_mrtrix/average_response_wm.txt) contains 2 lines, respectively with 1 and 1 coefficients. A minimum of 5 coefficients (lmax at least 8) is required for each line, and the number of coefficients has to match for both lines.
```

...is that `average_response_wm.txt` indeed has 2 lines, which is the correct and expected bit (one line for each b-value, so the first line goes with b=0, and the second line goes with b=1000).

However, it also says that each line only has 1 coefficient: that's the case for *isotropic* response functions.  By default `dwi2response dhollander` provides you with an *anisotropic* WM response function and *isotropic* GM and CSF response functions.  This is also what SS3T-CSD is expecting (and checking) for input.  So I was going to first ask to retrace your steps to see how `average_response_wm.txt` came to be isotropic... until I found the answer in the first comment line (what a lucky coincidence that line actually came in handy here 🙂): it looks like you've accidentally averaged all individual *GM* responses, and saved that as `average_response_wm.txt`.  It should be fixed if you use the WM responses of course.

By the way, if you want me to take a brief look / sensibility check at your (fixed) `average_response_wm.txt`, `average_response_gm.txt` and `average_response_csf.txt`; feel free to post them all 3 here.  I know what those numbers should more or less look like, relative to each other and for b=0 and b=1000.

**Comment by atefbadji** [comment] 2020-01-30 14:45
" **This command has also changed to a new name** (which means you can't be mistaken at least): it's now `responsemean" -> Great, thank you! I just tested it and it works

**Comment by thijsdhollander** [comment] 2020-02-01 05:11
Yep, it's an important one you'll almost always need in any group-wise analysis: to make SS3T-CSD results directly comparable *between* subjects, the SS3T-CSD has to be run with the same set of WM, GM and CSF response functions for all subjects.  The mean/average is just one arbitrary way to get one such unique set of the 3-tissue response functions for all subjects.  I will introduce something better at some point, but for the time being, the mean/average works just fine for this purpose. 😉

**Closed** 2020-02-07 00:57 UTC
Labels: question
